[package]
name = "small_dat"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = { workspace = true }

tokio = { version = "1", features = ["full"] }
anyhow = { version = "1.0" }
